server {
  listen 80;

  root /usr/share/nginx/html;

  location = /health {
    default_type application/json;
    return 200 '{"status":"ok"}';
  }

  location /config/ {
    try_files $uri =404;
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}