# docker-compose.yml

# version: "3.8"

services:
  single-beacon-demo:
    build: ./client
    container_name: single-beacon-demo
    ports:
      - "3000:3000"
    volumes:
      - ./feedback-data:/client/data
